apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sPSPSeccomp
metadata:
  name: require-seccomp-profile
spec:
  enforcementAction: deny
  match:
    kinds:
      - apiGroups: ["apps"]
        kinds: ["Deployment", "StatefulSet", "DaemonSet"]
      - apiGroups: [""]
        kinds: ["Pod"]
  parameters:
    allowedProfiles:
    - "runtime/default"
    - "RuntimeDefault"
    exemptNamespaces:
      - istio-system
      - istio-operator
      - kube-system
      - gatekeeper-system
      - team1
      - team2
