apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sRequiredProbes
metadata:
  name: enforce-readiness-liveness
spec:
  enforcementAction: deny
  match:
    kinds:
      - apiGroups: ["apps"]
        kinds: ["Deployment", "StatefulSet", "DaemonSet"]
      - apiGroups: [""]
        kinds: ["Pod"]
  parameters:
    exemptNamespaces:
      - istio-system
      - istio-operator
      - kube-system
      - gatekeeper-system
      - aws-node-termination-handler
      - aws-load-balancer-controller
      - karpenter
      - team1
      - team2
    excludeContainers:
      - "istio-proxy"
      - "istio-init"
      - "linkerd-proxy"
      - "linkerd-init"
      - "vault-agent"
      - "consul-connect-inject-init"
      - "aws-xray-daemon"
      - "fluent-bit"
      - "datadog-agent"
