apiVersion: constraints.gatekeeper.sh/v1beta1
kind: IstioMTLSRequired
metadata:
  name: require-istio-mtls
spec:
  enforcementAction: deny
  match:
    kinds:
      - apiGroups: ["networking.istio.io"]
        kinds: ["DestinationRule"]
  parameters:
    exemptNamespaces:
      - istio-system
      - istio-operator
      - kube-system
      - gatekeeper-system
      - team1
      - team2