apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sRestrictServiceExternal
metadata:
  name: deny-nodeports
spec:
  enforcementAction: deny
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Service"]
  parameters:
    types:
      - NodePort
    exemptNamespaces:
      - istio-system
      - istio-operator
      - kube-system
      - gatekeeper-system
      - team1
      - team2