apiVersion: v1
kind: ResourceQuota
metadata:
  name: team-quota
  namespace: {{ .Values.namespace }}
spec:
  hard:
    requests.cpu: "5"
    requests.memory: 8Gi
    limits.cpu: "9"
    limits.memory: 16Gi
    pods: "50"
