apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: google-external
spec:
  hosts:
  - www.google.com
  ports:
  - number: 443
    name: https
    protocol: HTTPS
  location: MESH_EXTERNAL
  resolution: DNS
##---
##apiVersion: networking.istio.io/v1beta1
##kind: DestinationRule
##metadata:
##  name: google-external-dr
##spec:
##  host: www.google.com
##  trafficPolicy:
##    tls:
##      mode: SIMPLE  # Use simple TLS for external HTTPS services
##      sni: www.google.com