apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app1-NAMESPACE
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@bitbucket.org:slalom-consulting/demo.git
    path: manifests/sample-apps/app1
    targetRevision: HEAD
    helm:
      values: |
        customerService:
          hostname: HOSTNAME
        resources:
          requests:
            cpu: "20m"
            memory: "96Mi"
          limits:
            cpu: "60m"
            memory: "256Mi"
  destination:
    server: https://kubernetes.default.svc
    namespace: NAMESPACE
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - LabelNamespace=istio-injection=enabled